### ISSUE TITLE
Dictating the Windows SDK version

### ISSUE THREAD

**Issue by JulianEr** [AKEngels/CAST#28]
Why do we dictate the Windows SDK version to be 10.0.18362.0? This makes CAST not compile with VS 2017 which is pretty new. If I comment out the systemversion parts in the lua-file it works like a charm. Would be nice if we coul remove those parts but, if I recall correctly, there were some problems as soon as I remove them?

**Comment by S0S-90** [comment]
I think it was me who inserted this because something didn't work back then. I tried it again with the systemversion lines outcommented and it now also worked for me with VS 2019 so I removed them now.

(When I added those lines I didn't add them out of nowhere but replaced some pretty complicated code by it which was supposed to find the correct systemversion for itself which never worked for me.)
