### ISSUE TITLE
CAST does not find python modules on windows

### ISSUE THREAD

**Issue by S0S-90** [AKEngels/CAST#8]
When I compile CAST with python enabled on windows (32bit version as python is 32bit) all is fine but when I run it it doesn't find the python modules.

**Comment by JulianEr** [comment]
Does moving the modules to the project folder solve it? Since the purge of the history CAST.txt and so on need to be in this folder. Or at least on my system.
 

Gesendet: Donnerstag, 15. Februar 2018 um 15:10 Uhr
Von: "Susanne Sauer" <notifications@github.com>
An: AKEngels/CAST <CAST@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [AKEngels/CAST] CAST does not find python modules on windows (#8)


When I compile CAST with python enabled on windows (32bit version as python is 32bit) all is fine but when I run it it doesn't find the python modules.

**Comment by S0S-90** [comment]
The modules are in the folder CAST/optional_files/build/python_modules as they have alway been. On ECPC all still works. Also a .pyc file is created in this folder while CAST is running.

**Comment by S0S-90** [comment]
The exact error is: Ausnahmefehler bei 0x50DE6247 (python27.dll) in CAST_win_x86_python_release.exe: 0xC0000005: Zugriffsverletzung beim Lesen an Position 0x00000004

**Comment by S0S-90** [comment]
Seems to be an issue with 32 or 64 bit python.

**Comment by S0S-90** [comment]
After downloading the 64bit version of python from https://www.python.org/downloads/release/python-2714/ I got a more helpful error message. It seems something either in C++ or in python for windows has changed in the way the python path is read into C++. Now everything should work again on windows as well as on linux.
